# Generated by Django 2.2.1 on 2020-03-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='description',
            field=models.CharField(default='Yo', max_length=500),
            preserve_default=False,
        ),
    ]
