# Generated by Django 2.2.1 on 2020-03-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_membership_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='rank',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
